In [1]:
import numpy as np

In [ ]:
# Template for note
'''
Mục đích: 
Code: 
'''
print('Array_1: ', )
print('Array_2: ', )
print('Array_3: ', )

## **Mảng 1 chiều**

### **Tạo mảng**

In [ ]:
'''
Mục đích: Tạo mảng một chiều từ range
Code: np.arrange(start, stop, step, dtype)
'''
print('Array_1: ', np.arange(10, 20))
print('Array_2: ', np.arange(10, 20, 2, np.float64))

Array_1:  [10 11 12 13 14 15 16 17 18 19]
Array_2:  [10. 12. 14. 16. 18.]


In [23]:
'''
Mục đích: Tạo mảng có khoảng cách đều nhau từ range
Code: np.linspace(start, stop, num, endpoint, dtype, retstep)
'''
print('Array_1: ', np.linspace(10, 20, 5)) # tính theo điểm
print('Array_2: ', np.linspace(10, 20, 5, endpoint=False)) # tính theo khoảng
print('Array_3: ', np.linspace(10, 20, 5, retstep=True)) # trả về khoảng cách

Array_1:  [10.  12.5 15.  17.5 20. ]
Array_2:  [10. 12. 14. 16. 18.]
Array_3:  (array([10. , 12.5, 15. , 17.5, 20. ]), np.float64(2.5))


In [ ]:
'''
np.array() và np.asarray()
'''
print('Array_1: ', np.array([1, 2, 3, 4])) # list
print('Array_2: ', np.asarray((1, 2, 3, 4))) # tuple

Array_1:  [1 2 3 4]
Array_2:  [1 2 3 4]


In [ ]:
'''
Mục đích: Tạo giá trị giả
Code: 
    + np.ones((row_num, col_num), dtype) : Toàn 1
    + np.zeros((row_num, col_num), dtype) : Toàn 0
'''
print('Array_1: \n', np.ones((2, 3)))
print('Array_2: \n', np.zeros((2, 3)))

Array_1: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Array_2: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [128]:
'''
Mục đích: Tạo mảng sẵn chưa giá trị để append
'''
print('Array_1: ', np.empty(shape=(0, 0)))

Array_1:  []


#### **Tạo mảng bằng random**

In [81]:
'''
Mục đích: Tạo mảng với giá trị ngẫu nhiên 
Code: 
    + np.random.rand(row_num, col_num) : Random trong [0, 1]
    + np.random.randint(low, high, size=(row_num, col_num)) : Random từ low -> high
'''
print('Array_1: \n', np.random.rand(3, 2))
print('Array_2: \n', np.random.randint(10, size=(3, 2))) # 1 value thì mặc định high
print('Array_3: \n', np.random.randint(1, 10, size=(3, 2)))

Array_1: 
 [[0.16560676 0.62329445]
 [0.86578973 0.0930867 ]
 [0.93316751 0.37799328]]
Array_2: 
 [[2 8]
 [3 6]
 [0 2]]
Array_3: 
 [[8 3]
 [2 1]
 [1 2]]


### **Hàm thống kê**

In [ ]:
'''
Mục đích: Tính toán
Code: # Viết np.mean(arr) hoặc arr.mean()
    + np.mean(arr) 
    + np.max(arr), np.min(arr)
    + ...

'''
arr_thong_ke = np.random.randint(20, size=(3, 2))
print('Array: \n', arr_thong_ke)

print('Mean: ', arr_thong_ke.mean())
print('Mean axis = 0 (tính từng column): ', arr_thong_ke.mean(axis=0)) # tính từng column
print('Mean axis = 1 (tính từng row): ', arr_thong_ke.mean(axis=1)) # tính từng row

print('Median: ', np.median(arr_thong_ke)) # median k xài đc arr.median()

print('Max: ', np.max(arr_thong_ke))
print('AMax: ', np.amax(arr_thong_ke))

# Peason correlation
arr_coefficient = np.array([
    [1, 4, 6, 7],
    [1, 2, 3, 4]
])
print('Coefficient: \n', np.corrcoef(arr_coefficient[0], arr_coefficient[1]))

# Tương tự mấy cái khác

Array: 
 [[ 0  1]
 [18 18]
 [ 0 13]]
Mean:  8.333333333333334
Mean axis = 0 (tính từng column):  [ 6.         10.66666667]
Mean axis = 1 (tính từng row):  [ 0.5 18.   6.5]
Median:  7.0
Max:  18
AMax:  18
Coefficient: 
 [[1.         0.97590007]
 [0.97590007 1.        ]]


### **Lọc điều kiện**

In [ ]:
'''
Mục đích: Filter các phần tử trong mảng với điều kiện
Code:
    + arr[arr > ...]
    + arr[(arr > ...) & (arr < ...)] : Nhiều điều kiện PHẢI CÓ NGOẶC
Lưu ý: & and, | or, ~ not
'''
arr_filters = np.random.randint(100, size=(20, ))
print('Array: ', arr_filters)
print('Marks T-F: ', arr_filters > 50)
print('Filter_1: ', arr_filters[arr_filters > 50])
print('Filter_2: ', arr_filters[(arr_filters > 50) & (arr_filters < 70)])

Array:  [93 42 20 14 69 47 66 55 11 26  0 91 29 36 40 24 13 55  0 34]
Marks T-F:  [ True False False False  True False  True  True False False False  True
 False False False False False  True False False]
Filter_1:  [93 69 66 55 91 55]
Filter_2:  [69 66 55 55]


### **Thao tác trên mảng**

In [131]:
'''
Mục đích: Thao tác mảng
Code:
    + np.append(arr, num)
    + np.insert(arr, idx, num)
    + np.delete(arr, idx)
    + ...
Lưu ý: Thao tác KHÔNG THAY ĐỔI DỮ LIỆU GỐC
'''
arr_thao_tac = np.random.randint(10, size=(10, ))
print('Array: ', arr_thao_tac)
print('Append: ', np.append(arr_thao_tac, 1000))
print('Insert: ', np.insert(arr_thao_tac, 1, 1000))
print('Delete: ', np.delete(arr_thao_tac, 0))

print('Sort (tăng dần): ', np.sort(arr_thao_tac))
print('Sort (giảm dần): ', np.sort(arr_thao_tac)[::-1])

arr_thao_tac_intersect = np.array([1, 2, 3, 4, 5])
print('Intersect: ', np.intersect1d(arr_thao_tac, arr_thao_tac_intersect)) # A giao B (lấy A)

arr_thao_tac_diff = np.array([1, 2, 3, 4, 5])
print('Diff: ', np.setdiff1d(arr_thao_tac, arr_thao_tac_intersect)) # A khác B (lấy A)

Array:  [1 6 0 9 7 7 6 6 5 9]
Append:  [   1    6    0    9    7    7    6    6    5    9 1000]
Insert:  [   1 1000    6    0    9    7    7    6    6    5    9]
Delete:  [6 0 9 7 7 6 6 5 9]
Sort (tăng dần):  [0 1 5 6 6 6 7 7 9 9]
Sort (giảm dần):  [9 9 7 7 6 6 6 5 1 0]
Intersect:  [1 5]
Diff:  [0 6 7 9]


### **Mảng dữ liệu tự định nghĩa**

In [ ]:
'''
Mục đích: Định nghĩa type (thường k xài, chủ yếu pandas)
Code:
    + np.dtype([(name_col_1, type), (name_col_2, type)])
'''
dt = np.dtype([('age', np.int8)])
arr_set_dt = np.array([(10, ), (20, ), (30, )], dtype=dt)
print(arr_set_dt['age'])

[10 20 30]


### **Một vài hàm**

In [98]:
arr_func = np.random.randint(10, size=(12, ))
print('Array: ', arr_func)

print('Reshape (normal): \n', arr_func.reshape(3, 4)) # phải đủ với số phần tử
print('Reshape (auto): \n', arr_func.reshape(-1, 2)) # đặt -1 là tự xác định

Array:  [5 9 2 2 2 6 2 6 0 0 7 6]
Reshape (normal): 
 [[5 9 2 2]
 [2 6 2 6]
 [0 0 7 6]]
Reshape (auto): 
 [[5 9]
 [2 2]
 [2 6]
 [2 6]
 [0 0]
 [7 6]]


## **Mảng nhiều chiều**

In [85]:
arr_nhieu_chieu = np.random.randint(10, size=(3, 3, 3))
print('Array: \n', arr_nhieu_chieu)

Array: 
 [[[1 2 6]
  [2 2 2]
  [8 3 7]]

 [[9 7 8]
  [8 3 2]
  [6 9 4]]

 [[8 9 4]
  [9 6 1]
  [8 3 5]]]


In [92]:
'''
Xem lại axis tính :
    - Tưởng tượng không gian 3 chiều với data như append dần dần
    - Các chiều (tưởng tượng giá trị dồn lại 2 chiều):
        + 0 : Trước mặt
        + 1 : Mặt trên
        + 2 : Mặt trái
'''
print('Sum (axis = 0): \n', np.sum(arr_nhieu_chieu, axis=0))
print('Sum (axis = 1): \n', np.sum(arr_nhieu_chieu, axis=1))
print('Sum (axis = 2): \n', np.sum(arr_nhieu_chieu, axis=2))

Sum (axis = 0): 
 [[18 18 18]
 [19 11  5]
 [22 15 16]]
Sum (axis = 1): 
 [[11  7 15]
 [23 19 14]
 [25 18 10]]
Sum (axis = 2): 
 [[ 9  6 18]
 [24 13 19]
 [21 16 16]]
